language: ruby
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
env:
  - NEO4J_VERSION=1.7.2
  - NEO4J_VERSION=1.8
before_script:
  - sh -c "rake neo4j:install[community,$NEO4J_VERSION]"
  - rake neo4j:start
